name: UHI Data Collector

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch:      # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run collector
        run: python uhi_collector.py
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

      - name: Commit and Push CSV
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add uhi_india_dataset.csv
          git commit -m "Auto-update UHI data" || exit 0
          git push